name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '15 3 * * *'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          # Plugin loading does not seem to work here.
          # "ImportError: cannot import name find_namespace_packages"
          # - "2.7"
          - "3.8"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Test Dependencies
        run: |
          pip install black pytest .
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Lint code
        run: black --diff --check .
      - name: Run tests
        run: |
          df -h
          cp tests/scripts/config.sh.example tests/scripts/config.sh
          .ci/run_container.sh pytest -v
