name: Nightly

on:
  schedule:
    - cron: '* * * * *'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'
  CONTAINER_RUNTIME: 'docker'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pulpcore:
          - "~=3.6"
          - "~=3.7"
          - "~=3.8"
          - "<4.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Test Dependencies
        run: pip install -r test_requirements.txt
      - name: Run tests
        env:
          PULPCORE_VERSION: {{ matrix.pulpcore }}
        run: .ci/run_container.sh make test

