name: Nightly Test

on:
  schedule:
    - cron: '15 3 * * *'

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'
  CONTAINER_RUNTIME: 'docker'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - "latest"
          - "3.8"
          - "3.7"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Test Dependencies
        run: pip install -r test_requirements.txt
      - name: Run tests
        env:
          IMAGE_TAG: ${{ matrix.image_tag }}
        run: .ci/run_container.sh make test
